name: TheRoadPlugin
version: '${project.version}'
main: me.supdapillar.theroad.TheRoadPlugin
api-version: '1.20'
authors: [Supdapillar]
description: For my minecraft minigame
commands:
  MakeSpawn:
    description: Makes an enemy spawnpoint
    permission: TheRoadPlugin.op
  ChangeWorld:
    description: Change what world your in
    permission: TheRoadPlugin.op
  MakeBlockage:
    description: makes a blockage that the player cant go through until the round is cleared
    permission: TheRoadPlugin.op
  MakeRespawnBeacon:
    description: Makes the armor stand the player has to click to enter the respawn event
    permission: TheRoadPlugin.op
  MakeCursedTreasure:
    description: Makes the armor stand the player has to click to enter the cursed treasure event
    permission: TheRoadPlugin.op
  MakeLootGenerator:
    description: Makes an armorstand that has a chance to generator a falling chest entity that can be click for loot
    permission: TheRoadPlugin.op
  MakeChallenge:
    description: Make an armorstand that has the challenge data
    permission: TheRoadPlugin.op
  MakeShrine:
      description: Make a textdisplay with shrine data
      permission: TheRoadPlugin.op
  Debug:
    description: Debug command to help me test some things
    permission: TheRoadPlugin.op
