name: TheRoadPlugin
version: '${project.version}'
main: me.supdapillar.theroad.TheRoadPlugin
api-version: '1.20'
authors: [Supdapillar]
description: For my minecraft minigame
commands:
  MakeSpawn:
    description: Makes an enemy spawnpoint
  ChangeWorld:
    description: Change what world your in
  MakeBlockage:
    description: makes a blockage that the player cant go through until the round is cleared
  MakeRespawnBeacon:
    description: Makes the armor stand the player has to click to enter the respawn event
  MakeCursedTreasure:
      description: Makes the armor stand the player has to click to enter the cursed treasure event
  MakeLootGenerator:
      description: Makes an armorstand that has a chance to generator a falling chest entity that can be click for loot
  MakeChallenge:
      description: Make an armorstand that has the challenge data
  Debug:
      description: Debug command to help me test some things